#  SERVER
server.port=8080
spring.application.name=apimovimentacaofinanceira

#  DATASOURCE (PostgreSQL)
spring.datasource.url=jdbc:postgresql://localhost:5432/db_movimentacao
spring.datasource.username=postgres
spring.datasource.password=LUAN123
spring.datasource.driverClassName=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
